/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.warehouse;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Insert object.
 */
public class Repository implements org.apache.thrift.TBase<Repository, Repository._Fields>, java.io.Serializable, Cloneable, Comparable<Repository> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Repository");

  private static final org.apache.thrift.protocol.TField URI_FIELD_DESC = new org.apache.thrift.protocol.TField("uri", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RAW_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("rawData", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PARSED_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("parsedData", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField UPDATE_VISIBILITY_FIELD_DESC = new org.apache.thrift.protocol.TField("updateVisibility", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RepositoryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RepositoryTupleSchemeFactory());
  }

  public String uri; // required
  public ByteBuffer rawData; // required
  public ByteBuffer parsedData; // required
  /**
   * Update visibility of old versions of this uri if its different from the new one.
   * Old visibility is changed even when making exclusive parsed or raw updates.
   */
  public boolean updateVisibility; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    URI((short)1, "uri"),
    RAW_DATA((short)2, "rawData"),
    PARSED_DATA((short)3, "parsedData"),
    /**
     * Update visibility of old versions of this uri if its different from the new one.
     * Old visibility is changed even when making exclusive parsed or raw updates.
     */
    UPDATE_VISIBILITY((short)4, "updateVisibility");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // URI
          return URI;
        case 2: // RAW_DATA
          return RAW_DATA;
        case 3: // PARSED_DATA
          return PARSED_DATA;
        case 4: // UPDATE_VISIBILITY
          return UPDATE_VISIBILITY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UPDATEVISIBILITY_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.UPDATE_VISIBILITY};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.URI, new org.apache.thrift.meta_data.FieldMetaData("uri", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RAW_DATA, new org.apache.thrift.meta_data.FieldMetaData("rawData", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.PARSED_DATA, new org.apache.thrift.meta_data.FieldMetaData("parsedData", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.UPDATE_VISIBILITY, new org.apache.thrift.meta_data.FieldMetaData("updateVisibility", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Repository.class, metaDataMap);
  }

  public Repository() {
    this.updateVisibility = false;

  }

  public Repository(
    String uri,
    ByteBuffer rawData,
    ByteBuffer parsedData)
  {
    this();
    this.uri = uri;
    this.rawData = rawData;
    this.parsedData = parsedData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Repository(Repository other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetUri()) {
      this.uri = other.uri;
    }
    if (other.isSetRawData()) {
      this.rawData = org.apache.thrift.TBaseHelper.copyBinary(other.rawData);
;
    }
    if (other.isSetParsedData()) {
      this.parsedData = org.apache.thrift.TBaseHelper.copyBinary(other.parsedData);
;
    }
    this.updateVisibility = other.updateVisibility;
  }

  public Repository deepCopy() {
    return new Repository(this);
  }

  @Override
  public void clear() {
    this.uri = null;
    this.rawData = null;
    this.parsedData = null;
    this.updateVisibility = false;

  }

  public String getUri() {
    return this.uri;
  }

  public Repository setUri(String uri) {
    this.uri = uri;
    return this;
  }

  public void unsetUri() {
    this.uri = null;
  }

  /** Returns true if field uri is set (has been assigned a value) and false otherwise */
  public boolean isSetUri() {
    return this.uri != null;
  }

  public void setUriIsSet(boolean value) {
    if (!value) {
      this.uri = null;
    }
  }

  public byte[] getRawData() {
    setRawData(org.apache.thrift.TBaseHelper.rightSize(rawData));
    return rawData == null ? null : rawData.array();
  }

  public ByteBuffer bufferForRawData() {
    return rawData;
  }

  public Repository setRawData(byte[] rawData) {
    setRawData(rawData == null ? (ByteBuffer)null : ByteBuffer.wrap(rawData));
    return this;
  }

  public Repository setRawData(ByteBuffer rawData) {
    this.rawData = rawData;
    return this;
  }

  public void unsetRawData() {
    this.rawData = null;
  }

  /** Returns true if field rawData is set (has been assigned a value) and false otherwise */
  public boolean isSetRawData() {
    return this.rawData != null;
  }

  public void setRawDataIsSet(boolean value) {
    if (!value) {
      this.rawData = null;
    }
  }

  public byte[] getParsedData() {
    setParsedData(org.apache.thrift.TBaseHelper.rightSize(parsedData));
    return parsedData == null ? null : parsedData.array();
  }

  public ByteBuffer bufferForParsedData() {
    return parsedData;
  }

  public Repository setParsedData(byte[] parsedData) {
    setParsedData(parsedData == null ? (ByteBuffer)null : ByteBuffer.wrap(parsedData));
    return this;
  }

  public Repository setParsedData(ByteBuffer parsedData) {
    this.parsedData = parsedData;
    return this;
  }

  public void unsetParsedData() {
    this.parsedData = null;
  }

  /** Returns true if field parsedData is set (has been assigned a value) and false otherwise */
  public boolean isSetParsedData() {
    return this.parsedData != null;
  }

  public void setParsedDataIsSet(boolean value) {
    if (!value) {
      this.parsedData = null;
    }
  }

  /**
   * Update visibility of old versions of this uri if its different from the new one.
   * Old visibility is changed even when making exclusive parsed or raw updates.
   */
  public boolean isUpdateVisibility() {
    return this.updateVisibility;
  }

  /**
   * Update visibility of old versions of this uri if its different from the new one.
   * Old visibility is changed even when making exclusive parsed or raw updates.
   */
  public Repository setUpdateVisibility(boolean updateVisibility) {
    this.updateVisibility = updateVisibility;
    setUpdateVisibilityIsSet(true);
    return this;
  }

  public void unsetUpdateVisibility() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UPDATEVISIBILITY_ISSET_ID);
  }

  /** Returns true if field updateVisibility is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdateVisibility() {
    return EncodingUtils.testBit(__isset_bitfield, __UPDATEVISIBILITY_ISSET_ID);
  }

  public void setUpdateVisibilityIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UPDATEVISIBILITY_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case URI:
      if (value == null) {
        unsetUri();
      } else {
        setUri((String)value);
      }
      break;

    case RAW_DATA:
      if (value == null) {
        unsetRawData();
      } else {
        setRawData((ByteBuffer)value);
      }
      break;

    case PARSED_DATA:
      if (value == null) {
        unsetParsedData();
      } else {
        setParsedData((ByteBuffer)value);
      }
      break;

    case UPDATE_VISIBILITY:
      if (value == null) {
        unsetUpdateVisibility();
      } else {
        setUpdateVisibility((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case URI:
      return getUri();

    case RAW_DATA:
      return getRawData();

    case PARSED_DATA:
      return getParsedData();

    case UPDATE_VISIBILITY:
      return Boolean.valueOf(isUpdateVisibility());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case URI:
      return isSetUri();
    case RAW_DATA:
      return isSetRawData();
    case PARSED_DATA:
      return isSetParsedData();
    case UPDATE_VISIBILITY:
      return isSetUpdateVisibility();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Repository)
      return this.equals((Repository)that);
    return false;
  }

  public boolean equals(Repository that) {
    if (that == null)
      return false;

    boolean this_present_uri = true && this.isSetUri();
    boolean that_present_uri = true && that.isSetUri();
    if (this_present_uri || that_present_uri) {
      if (!(this_present_uri && that_present_uri))
        return false;
      if (!this.uri.equals(that.uri))
        return false;
    }

    boolean this_present_rawData = true && this.isSetRawData();
    boolean that_present_rawData = true && that.isSetRawData();
    if (this_present_rawData || that_present_rawData) {
      if (!(this_present_rawData && that_present_rawData))
        return false;
      if (!this.rawData.equals(that.rawData))
        return false;
    }

    boolean this_present_parsedData = true && this.isSetParsedData();
    boolean that_present_parsedData = true && that.isSetParsedData();
    if (this_present_parsedData || that_present_parsedData) {
      if (!(this_present_parsedData && that_present_parsedData))
        return false;
      if (!this.parsedData.equals(that.parsedData))
        return false;
    }

    boolean this_present_updateVisibility = true && this.isSetUpdateVisibility();
    boolean that_present_updateVisibility = true && that.isSetUpdateVisibility();
    if (this_present_updateVisibility || that_present_updateVisibility) {
      if (!(this_present_updateVisibility && that_present_updateVisibility))
        return false;
      if (this.updateVisibility != that.updateVisibility)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Repository other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUri()).compareTo(other.isSetUri());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUri()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uri, other.uri);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRawData()).compareTo(other.isSetRawData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRawData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rawData, other.rawData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParsedData()).compareTo(other.isSetParsedData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParsedData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parsedData, other.parsedData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUpdateVisibility()).compareTo(other.isSetUpdateVisibility());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdateVisibility()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updateVisibility, other.updateVisibility);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Repository(");
    boolean first = true;

    sb.append("uri:");
    if (this.uri == null) {
      sb.append("null");
    } else {
      sb.append(this.uri);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rawData:");
    if (this.rawData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.rawData, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("parsedData:");
    if (this.parsedData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.parsedData, sb);
    }
    first = false;
    if (isSetUpdateVisibility()) {
      if (!first) sb.append(", ");
      sb.append("updateVisibility:");
      sb.append(this.updateVisibility);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (uri == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'uri' was not present! Struct: " + toString());
    }
    if (rawData == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'rawData' was not present! Struct: " + toString());
    }
    if (parsedData == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'parsedData' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RepositoryStandardSchemeFactory implements SchemeFactory {
    public RepositoryStandardScheme getScheme() {
      return new RepositoryStandardScheme();
    }
  }

  private static class RepositoryStandardScheme extends StandardScheme<Repository> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Repository struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // URI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.uri = iprot.readString();
              struct.setUriIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RAW_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.rawData = iprot.readBinary();
              struct.setRawDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PARSED_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.parsedData = iprot.readBinary();
              struct.setParsedDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // UPDATE_VISIBILITY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.updateVisibility = iprot.readBool();
              struct.setUpdateVisibilityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Repository struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.uri != null) {
        oprot.writeFieldBegin(URI_FIELD_DESC);
        oprot.writeString(struct.uri);
        oprot.writeFieldEnd();
      }
      if (struct.rawData != null) {
        oprot.writeFieldBegin(RAW_DATA_FIELD_DESC);
        oprot.writeBinary(struct.rawData);
        oprot.writeFieldEnd();
      }
      if (struct.parsedData != null) {
        oprot.writeFieldBegin(PARSED_DATA_FIELD_DESC);
        oprot.writeBinary(struct.parsedData);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUpdateVisibility()) {
        oprot.writeFieldBegin(UPDATE_VISIBILITY_FIELD_DESC);
        oprot.writeBool(struct.updateVisibility);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RepositoryTupleSchemeFactory implements SchemeFactory {
    public RepositoryTupleScheme getScheme() {
      return new RepositoryTupleScheme();
    }
  }

  private static class RepositoryTupleScheme extends TupleScheme<Repository> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Repository struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.uri);
      oprot.writeBinary(struct.rawData);
      oprot.writeBinary(struct.parsedData);
      BitSet optionals = new BitSet();
      if (struct.isSetUpdateVisibility()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetUpdateVisibility()) {
        oprot.writeBool(struct.updateVisibility);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Repository struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.uri = iprot.readString();
      struct.setUriIsSet(true);
      struct.rawData = iprot.readBinary();
      struct.setRawDataIsSet(true);
      struct.parsedData = iprot.readBinary();
      struct.setParsedDataIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.updateVisibility = iprot.readBool();
        struct.setUpdateVisibilityIsSet(true);
      }
    }
  }

}

